travis:
  secure:
    BINSTAR_TOKEN: eN/LPd2+SXmlQaW4L1BmcgvqLxwmUleyCV9LjR2zGhIinVrI7+1EOgNgD5zBCWa77149DrusSdorzKdam4J+M+0kPFRmk9yZF9+hReTho+GkZvJDZhHaC8CTd1u80aar7pqXxFH1Ju0+eEqd5wMN3TnRof36+8sV+BTVbllxVYiH6xhCqieUrpQuA4CqqSh5JEuZiH1734YoL0LE6+ZItGQjr3fmqqXjPy0wVn1+MaP8X2aC4bP7rehQY2mpqK/HGpixhHt2/YwhyWIu7nW9CRZoKR4WDP+TmpWecXV5Pnhtzbx5oGLAW46zk5+NEG74qz12edscjd4HJpYK+ndpqHk2oM7JxBW519W7ECxtPqzktul7IBWjFOKRDOny57ExYfDqgWpvVgIIJmnrTiBP1CsMWwM45jtMvDoZ3XdE6jAHP8qEKKgNW7v7ePESfKd7gEOmq99xmNB/RZ0246XvlEq8A6bKfDVMfhP5zQKkNai/rIVRImHSHilG311ZOUpJ87PVcCdMAh96auvO5k4g1gE+KTjY2ggLqZXTRiSKD6kJG2ngT8XUZ0uTE1OrN/atht5aTDos4RS2ypynLbUZmiUHmavO4h4STH91cPbK1ehRL0mC6cGQ8T859EVU1k/pGRW8QJduC68fqsTtUhflEU8OgTRv4HcReHWJBKFwKmI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
