travis:
  secure:
    BINSTAR_TOKEN: nHlUMHk+EkZ/hs2zRD+LcN8OIV0lTPbot0x/z1EK6qnMyoK5Jh2hzC+d2K/G+giQtv8xESITokew4Nt5FYFw1P14ljAw6EKWA29Yk0tXPSVpOm08zgK0qDKzACPCxV/+O1Zl229J7mJ5EdA1X/8T2BkKNWaQ1bfCMwjn85Hr5oWEc92isS5vQ+wXgdWTCoMgPpN5/EgBoP9Xaz8K3NWKUsJg/BSryNDDmlwRsXlgESejcd/0mLKt8R4HjMsumX2QbF2Xq9xJdKPnxPwUhvuFuW5tn9MqPMBBfRBBtqhljpTz5ECTqODlpoquMOiIjfTAKGxU+0adm+c/6C1yR8Xhn7qeshrxcJEN4Ez1wgthZCMO+V+XuzvbVa8/FRmN1WfrKjQMJxEY6eGYRW0+nZDLnAUd/dT+brUpcBo/q6bIdPijduh3Q6ZFuyXQsMA3OPte6iAyzXOwW6zmrXve21lj2e5aSoEvT/C9aF1dROw9D3UP24OVZub3ApZMb3vxgGSstZTKH8FLKKVxyt+H+wE1eyrJFrsWohfBJ96SE3xA9Q6Ts6ofHosK3uQgps23+PT0oM4ERd6L+XUQE03tV66IFmuEyJc42I4Tewx0lOpd7Xwxk5d8ixT9qTvGIemb8nOSMOq3Z6U/DpQq86hpStiJIKfPIDvQaLd86jOnSQmlBmU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
